name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: biomejs/setup-biome@v2

      - run: pnpm i
      - run: biome ci .
      - run: pnpx jsr publish
